//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class au_menu
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string url { get; set; }
        public int parentId { get; set; }
    }
}
